; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino



; 시리얼 모니터 속도 설정 (필요시 추가)
monitor_speed = 9600

; 어셈블리 코드를 확인
build_flags =
    -save-temps=obj
    -fverbose-asm
    -Wno-incompatible-pointer-types ; 4-1 경고 숨기기

;task_main.cpp  에서 사용
lib_deps =
    arkhipenko/TaskScheduler @ ^3.7.0
    ;DHT sensor  에서 사용
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    ;servo motor
    arduino-libraries/Servo @ ^1.2.1
    ;라이브러리 공식 명칭 또는 주소 (예시)
    https://github.com/MakerSpaceLeiden/rfid.git
    ;lcd1602 + LiquidCrystal I2C
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    